config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :waifus do
    resources :ratings
  end

  root 'waifus#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
  # belongs_to :user
  belongs_to :waifu
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ratings, dependent: :destroy
  has_one_attached :avatar
end

app/models/waifu.rb
class Waifu < ApplicationRecord
  has_many :ratings, dependent: :destroy
  has_one_attached :image

  validates :name, presence: true, length: { minimum: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @waifu = Waifu.find(params[:waifu_id])
    @rating = @waifu.ratings.create(rating_params)

    # user controller

    redirect_to waifu_path(@waifu)
  end

  def destroy
    @waifu = Waifu.find(params[:waifu_id])
    @rating = @waifu.ratings.find(params[:id])
    @rating.destroy
    redirect_to waifu_path(@waifu)
  end

  private
  def rating_params
    params.require(:rating).permit(:waifu_rating)
  end
end

app/controllers/waifus_controller.rb
class WaifusController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @waifus = Waifu.all
  end

  def show
    @waifu = Waifu.find(params[:id])
  end

  def new
    @waifu = Waifu.new
  end

  def edit
    @waifu = Waifu.find(params[:id])
  end

  def create
    @waifu = Waifu.new(waifu_params)

    if @waifu.save
      redirect_to @waifu
    else
      render 'new'
    end
  end

  def update
    @waifu = Waifu.find(params[:id])

    if @waifu.update(waifu_params)
      redirect_to @waifu
    else
      render 'edit'
    end
  end

  def destroy
    @waifu = Waifu.find(params[:id])
    @waifu.destroy

    redirect_to waifus_path
  end

  private
    def waifu_params
      params.require(:waifu).permit(:name, :anime, :image_url, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/waifus_helper.rb
module WaifusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waifu4uRails6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ratings/_form.html.erb
<%= form_with(model: [ @waifu, @waifu.ratings.build ], local: true) do |form| %>
  <p>
    <%= form.label :waifu_rating %><br>
    <%= form.text_field :waifu_rating %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/ratings/_rating.html.erb
<p>
  <strong>Rating:</strong>
  <%= rating.waifu_rating %>
</p>

<p>
  <%= link_to 'Destroy Rating', [rating.waifu, rating],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/waifus/_form.html.erb
<%= form_with model: @waifu, local: true do |form| %>

  <% if @waifu.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@waifu.errors.count, "error") %> prohibited
        this waifu from being saved:
      </h2>
      <ul>
        <% @waifu.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :anime %><br>
    <%= form.text_field :anime %>
  </p>

  <p>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/waifus/edit.html.erb
<h1>Edit waifu</h1>

<%= render 'form' %>

<%= link_to 'Back', waifus_path %>

app/views/waifus/index.html.erb
<h1>Listing waifus</h1>

<%= link_to 'New waifu', new_waifu_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Anime</th>
    <th>Image_url</th>
    <th></th>
  </tr>

  <% @waifus.each do |waifu| %>
    <tr>
      <td><%= waifu.name %></td>
      <td><%= waifu.anime %></td>
      <td><%= link_to 'Show', waifu_path(waifu) %></td>
      <td><%= link_to 'Edit', edit_waifu_path(waifu) %></td>
      <td><%= link_to 'Destroy', waifu_path(waifu),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<button type="button" class="btn btn-primary">Primary</button>

app/views/waifus/new.html.erb
<%= form_with scope: :waifu, url: waifus_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :anime %><br>
    <%= form.text_field :anime %>
  </p>

  <p>
    <%= form.label :image_url %><br>
    <%= form.text_field :image_url %>
  </p>

  <p>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>


<%= link_to 'Back', waifus_path %>

app/views/waifus/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @waifu.name %>
</p>

<p>
  <strong>Anime:</strong>
  <%= @waifu.anime %>
</p>

<p>
  <strong>Image:</strong>
  <%= @waifu.image %>
</p>

<%= image_tag @waifu.image %>

<br>

<h2>Ratings</h2>
<%= render @waifu.ratings %>

<h2>Add a rating:</h2>
<%= render 'ratings/form' %>


<br>



<%= link_to 'Edit', edit_waifu_path(@waifu) %> |
<%= link_to 'Back', waifus_path %>

